import { Section } from '../types';

const class11PhysicsChapters = [
  { name: 'Units and Measurements' },
  { name: 'Motion in a Straight Line' },
  { name: 'Motion in a Plane' },
  { name: 'Laws of Motion' },
  { name: 'Work, Energy and Power' },
  { name: 'System of Particles and Rotational Motion' },
  { name: 'Gravitation' },
  { name: 'Mechanical Properties of Solids' },
  { name: 'Mechanical Properties of Fluids' },
  { name: 'Thermal Properties of Matter' },
  { name: 'Thermodynamics' },
  { name: 'Kinetic Theory' },
  { name: 'Oscillations' },
  { name: 'Waves' },
];

const class11ChemistryChapters = [
  { name: 'Some Basic Concepts of Chemistry' },
  { name: 'Structure of Atom' },
  { name: 'Classification of Elements and Periodicity in Properties' },
  { name: 'Chemical Bonding and Molecular Structure' },
  { name: 'States of Matter' },
  { name: 'Thermodynamics' },
  { name: 'Equilibrium' },
  { name: 'Redox Reactions' },
  { name: 'Hydrogen' },
  { name: 'The s-Block Elements' },
  { name: 'The p-Block Elements' },
  { name: 'Organic Chemistry: Some Basic Principles and Techniques' },
  { name: 'Hydrocarbons' },
  { name: 'Environmental Chemistry' },
];

const class11BiologyChapters = [
    { name: 'The Living World' },
    { name: 'Biological Classification' },
    { name: 'Plant Kingdom' },
    { name: 'Animal Kingdom' },
    { name: 'Morphology of Flowering Plants' },
    { name: 'Anatomy of Flowering Plants' },
    { name: 'Structural Organisation in Animals' },
    { name: 'Cell: The Unit of Life' },
    { name: 'Biomolecules' },
    { name: 'Cell Cycle and Cell Division' },
    { name: 'Transport in Plants' },
    { name: 'Mineral Nutrition' },
    { name: 'Photosynthesis in Higher Plants' },
    { name: 'Respiration in Plants' },
    { name: 'Plant Growth and Development' },
    { name: 'Digestion and Absorption' },
    { name: 'Breathing and Exchange of Gases' },
    { name: 'Body Fluids and Circulation' },
    { name: 'Excretory Products and their Elimination' },
    { name: 'Locomotion and Movement' },
    { name: 'Neural Control and Coordination' },
    { name: 'Chemical Coordination and Integration' },
];

const class11MathsChapters = [
    { name: 'Sets' },
    { name: 'Relations and Functions' },
    { name: 'Trigonometric Functions' },
    { name: 'Principle of Mathematical Induction' },
    { name: 'Complex Numbers and Quadratic Equations' },
    { name: 'Linear Inequalities' },
    { name: 'Permutations and Combinations' },
    { name: 'Binomial Theorem' },
    { name: 'Sequences and Series' },
    { name: 'Straight Lines' },
    { name: 'Conic Sections' },
    { name: 'Introduction to Three Dimensional Geometry' },
    { name: 'Limits and Derivatives' },
    { name: 'Mathematical Reasoning' },
    { name: 'Statistics' },
    { name: 'Probability' },
];


const class11EnglishChapters = [
  { name: 'The Portrait of a Lady' },
  { name: 'A Photograph (Poem)' },
  { name: 'We\'re Not Afraid to Die... if We Can All Be Together' },
  { name: 'Discovering Tut: the Saga Continues' },
  { name: 'The Laburnum Top (Poem)' },
  { name: 'The Voice of the Rain (Poem)' },
  { name: 'Childhood (Poem)' },
  { name: 'The Adventure' },
  { name: 'Silk Road' },
  { name: 'Father to Son (Poem)' },
];

const class12PhysicsChapters = [
  { name: 'Electric Charges and Fields' },
  { name: 'Electrostatic Potential and Capacitance' },
  { name: 'Current Electricity' },
  { name: 'Moving Charges and Magnetism' },
  { name: 'Magnetism and Matter' },
  { name: 'Electromagnetic Induction' },
  { name: 'Alternating Current' },
  { name: 'Electromagnetic Waves' },
  { name: 'Ray Optics and Optical Instruments' },
  { name: 'Wave Optics' },
  { name: 'Dual Nature of Radiation and Matter' },
  { name: 'Atoms' },
  { name: 'Nuclei' },
  { name: 'Semiconductor Electronics: Materials, Devices and Simple Circuits' },
];

const class12ChemistryChapters = [
  { name: 'The Solid State' },
  { name: 'Solutions' },
  { name: 'Electrochemistry' },
  { name: 'Chemical Kinetics' },
  { name: 'Surface Chemistry' },
  { name: 'General Principles and Processes of Isolation of Elements' },
  { name: 'The p-Block Elements' },
  { name: 'The d- and f-Block Elements' },
  { name: 'Coordination Compounds' },
  { name: 'Haloalkanes and Haloarenes' },
  { name: 'Alcohols, Phenols and Ethers' },
  { name: 'Aldehydes, Ketones and Carboxylic Acids' },
  { name: 'Amines' },
  { name: 'Biomolecules' },
  { name: 'Polymers' },
  { name: 'Chemistry in Everyday Life' },
];

const class12BiologyChapters = [
    { name: 'Reproduction in Organisms' },
    { name: 'Sexual Reproduction in Flowering Plants' },
    { name: 'Human Reproduction' },
    { name: 'Reproductive Health' },
    { name: 'Principles of Inheritance and Variation' },
    { name: 'Molecular Basis of Inheritance' },
    { name: 'Evolution' },
    { name: 'Human Health and Disease' },
    { name: 'Strategies for Enhancement in Food Production' },
    { name: 'Microbes in Human Welfare' },
    { name: 'Biotechnology: Principles and Processes' },
    { name: 'Biotechnology and its Applications' },
    { name: 'Organisms and Populations' },
    { name: 'Ecosystem' },
    { name: 'Biodiversity and Conservation' },
    { name: 'Environmental Issues' },
];

const class12MathsChapters = [
    { name: 'Relations and Functions' },
    { name: 'Inverse Trigonometric Functions' },
    { name: 'Matrices' },
    { name: 'Determinants' },
    { name: 'Continuity and Differentiability' },
    { name: 'Application of Derivatives' },
    { name: 'Integrals' },
    { name: 'Application of Integrals' },
    { name: 'Differential Equations' },
    { name: 'Vector Algebra' },
    { name: 'Three Dimensional Geometry' },
    { name: 'Linear Programming' },
    { name: 'Probability' },
];

const class12EnglishChapters = [
  { name: 'The Last Lesson' },
  { name: 'Lost Spring' },
  { name: 'Deep Water' },
  { name: 'The Rattrap' },
  { name: 'Indigo' },
  { name: 'Poets and Pancakes' },
  { name: 'The Interview' },
  { name: 'Going Places' },
  { name: 'My Mother at Sixty-six (Poem)' },
  { name: 'An Elementary School Classroom in a Slum (Poem)' },
  { name: 'Keeping Quiet (Poem)' },
  { name: 'A Thing of Beauty (Poem)' },
  { name: 'A Roadside Stand (Poem)' },
  { name: 'Aunt Jennifer\'s Tigers (Poem)' },
];

export const STUDY_SECTIONS: Section[] = [
  {
    name: 'Class 11',
    description: 'NCERT curriculum for 11th grade students.',
    subjects: [
      { name: 'Physics', chapters: class11PhysicsChapters },
      { name: 'Chemistry', chapters: class11ChemistryChapters },
      { name: 'Maths', chapters: class11MathsChapters },
      { name: 'Biology', chapters: class11BiologyChapters },
      { name: 'English', chapters: class11EnglishChapters },
    ],
  },
  {
    name: 'Class 12',
    description: 'NCERT curriculum for 12th grade students.',
    subjects: [
      { name: 'Physics', chapters: class12PhysicsChapters },
      { name: 'Chemistry', chapters: class12ChemistryChapters },
      { name: 'Maths', chapters: class12MathsChapters },
      { name: 'Biology', chapters: class12BiologyChapters },
      { name: 'English', chapters: class12EnglishChapters },
    ],
  },
  {
    name: 'NEET',
    description: 'Preparation material for medical entrance exams.',
    subjects: [
      { name: 'Physics', chapters: [...class11PhysicsChapters, ...class12PhysicsChapters] },
      { name: 'Chemistry', chapters: [...class11ChemistryChapters, ...class12ChemistryChapters] },
      { name: 'Biology', chapters: [...class11BiologyChapters, ...class12BiologyChapters] },
    ],
  },
  {
    name: 'JEE',
    description: 'Preparation material for engineering entrance exams.',
    subjects: [
      { name: 'Physics', chapters: [...class11PhysicsChapters, ...class12PhysicsChapters] },
      { name: 'Chemistry', chapters: [...class11ChemistryChapters, ...class12ChemistryChapters] },
      { name: 'Maths', chapters: [...class11MathsChapters, ...class12MathsChapters] },
    ],
  },
];